### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by erilun06** [BuiltBrokenModding/MFFS_Classic#27]
when I throw a frag grenade from classic this happens

Unreported exception thrown!
java.lang.NoSuchMethodError: resonant.api.explosion.ExplosionEvent$ExplosivePreDetonationEvent.<init>(Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;Lresonant/api/explosion/ExplosiveType;Lcom/builtbroken/mc/api/explosive/IExplosiveHandler;)V
	at icbm.classic.content.items.ItemGrenade.func_77659_a(ItemGrenade.java:63)
	at net.minecraft.item.ItemStack.func_77957_a(Unknown Source)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DarkGuardsman** [comment]
Most likely your voltz Engine version is outdated. Try updating to the latest alpha of both it and ICBM-Classic. If that doesn't work reply back with the versions you are using so I can check if the files built correctly.
