### ISSUE TITLE
Interdiction Matrix crash and more...

### ISSUE THREAD

**Issue by Aeon-Industries** [BuiltBrokenModding/MFFS_Classic#29]
Interdiction Matrix crashes server when a Force Field Projector is placed directly adjacent to it. Interdiction Matrix should have a module in it, preferably an "anti"-something. Frequency is ignored(intended behaviour?).

```
java.lang.NullPointerException: Ticking block entity
	at com.mffs.common.tile.TileFieldMatrix.getInteriorPoints(TileFieldMatrix.java:290)
	at com.mffs.common.tile.type.TileInterdictionMatrix.scan(TileInterdictionMatrix.java:135)
	at com.mffs.common.tile.type.TileInterdictionMatrix.func_145845_h(TileInterdictionMatrix.java:92)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
---
Also, there are a few other, less severe things:
- Disintegration field attempts to remove air blocks - and never succeeds;
- Force Field blocks generated after being broken in creative mode can not be sneaked through;
- Some modules have unexpected effects when placed in directional slots of the projector:
--    speed modules have no effect
--    repulsion mode causes field blocks to appear rapidly
--    disintegration module causes field blocks to appear and completely replace replaceable(not bedrock, projector, etc) blocks without dropping them;
- Bottom right slot of the 5x5 projector configuration grid behaves as if it is a directional slot(the issue above), however translation and scale modules placed in it have no effect;
- Field fusion module may cause some field blocks on the intersections to despawn on contact/bumping, some may stay in the world after both fields are disabled;
- Repulsion field doesn't seem to render(not optifine-friendly?) and causes npc entites to teleport through it;
- Interdiction Matrix doesn't collect drop from monsters even with collection module(intended?);
- "Use Forcefield Renderer" config option doesn't seem to have any noticeable effects(optifine, with and without shaders).

Issues seen on version 0.0.51b139, some of them have been also tested on build 143.

**Comment by Su5eD** [comment]
Closing as outdated.
