### ISSUE TITLE
Forcefield in cube mode crash

### ISSUE THREAD

**Issue by benbarbrooke** [BuiltBrokenModding/MFFS_Classic#31]
I get a crash when turning the forcefield on. I don't know if it has anything to do with the blcoks within the forcefield?

[20:26:10] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException
	at java.util.PriorityQueue.<init>(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.client.renderer.Tessellator.func_147564_a(Tessellator.java:160) ~[bmh.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147891_a(WorldRenderer.java:248) ~[blo.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:204) ~[blo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by DarkGuardsman** [comment]
Which version are you running?

**Comment by benbarbrooke** [comment]
Mffs-1.7.10-4.0.0b152

**Comment by DarkGuardsman** [comment]
Took me a bit to test the issue due to a cold. However, it looks like it has already been fixed in the rewrite branch.... but said branch has not be pushed to the build system yet. I need to finish a few GUI changes then it will be pushed and should solve the issue. Not sure how long this will take due to the cold I currently have.
