### ISSUE TITLE
Crashes when activating forcefield

### ISSUE THREAD

**Issue by Mobilfan** [BuiltBrokenModding/MFFS_Classic#39]

**Comment by DarkGuardsman** [comment]
Can't do anything without a crash report

**Comment by Mobilfan** [comment]
Sorry here it is:
`---- Minecraft Crash Report ----
// There are four lights!

Time: 08.09.18 22:43
Description: Exception while updating neighbours

java.lang.RuntimeException: Invalid ticket request
	at net.minecraftforge.common.ForgeChunkManager.requestTicket(ForgeChunkManager.java:664)
	at com.minalien.mffs.machines.TileEntityProjector.activate(TileEntityProjector.scala:169)
	at com.minalien.mffs.blocks.machines.BlockProjector$.func_149695_a(BlockProjector.scala:32)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:649)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:651)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:651)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.func_72921_c(World.java:553)
	at net.minecraft.block.BlockLever.func_149727_a(BlockLever.java:273)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.ForgeChunkManager.requestTicket(ForgeChunkManager.java:664)
	at com.minalien.mffs.machines.TileEntityProjector.activate(TileEntityProjector.scala:169)
	at com.minalien.mffs.blocks.machines.BlockProjector$.func_149695_a(BlockProjector.scala:32)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block type: ID #252 (tile.projector // com.minalien.mffs.blocks.machines.BlockProjector$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1948,52,784), Chunk: (at 12,3,0 in 121,49; contains blocks 1936,0,784 to 1951,255,799), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:649)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block data value: 12 / 0xC / 0b1100
	Block location: World: (1946,52,784), Chunk: (at 10,3,0 in 121,49; contains blocks 1936,0,784 to 1951,255,799), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:651)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block data value: 12 / 0xC / 0b1100
	Block location: World: (1946,52,784), Chunk: (at 10,3,0 in 121,49; contains blocks 1936,0,784 to 1951,255,799), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block data value: 13 / 0xD / 0b1101
	Block location: World: (1946,52,785), Chunk: (at 10,3,1 in 121,49; contains blocks 1936,0,784 to 1951,255,799), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:651)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:81)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)

-- Block being updated --
Details:
	Source block type: ID #69 (tile.lever // net.minecraft.block.BlockLever)
	Block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block data value: 13 / 0xD / 0b1101
	Block location: World: (1946,52,785), Chunk: (at 10,3,1 in 121,49; contains blocks 1936,0,784 to 1951,255,799), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.func_72921_c(World.java:553)
	at net.minecraft.block.BlockLever.func_149727_a(BlockLever.java:273)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@9303c31
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 470900368 bytes (449 MB) / 805306368 bytes (768 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	ConveyorCraft{0.01} [MrDimka's Conveyor Craft] ([1.7.10]+ConveyorCraft+-+0.01.jar) 
	UCHIJAAAA	securitycraft{v1.8.2.2} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.2.2.jar) 
	UCHIJAAAA	ModularForcefieldSystem{3.0-ALPHA-7} [Modular Forcefield System] (Modular-Forcefield-System-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Hummel100'/74, l='good base', x=1947,70, y=52,00, z=785,16]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by DarkGuardsman** [comment]
com.**minalien**.mffs.machines.TileEntityProjector

Based on the log, this is not our version of MFFS. Any project we develope will start with com.**builtbroken** 
https://github.com/BuiltBrokenModding/MFFS_Classic/tree/master/src/main/java/com/builtbroken/mffs

Sorry for the confusion that name has caused. There is roughly 5 different versions of MFFS that exist. The version your using I think may no longer even be supported. As I was unable to find a github for it and all links to it seem to be dead.
