### ISSUE TITLE
[NeoForge 1.20.1] EnableProjectorModeGlitch not working

### ISSUE THREAD

**Issue by halvors** [BuiltBrokenModding/MFFS_Classic#62]
With enableProjectorModeGlitch set to "true"  i get this crash when Minecraft starts

```
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-01-27 15:41:42
Description: Rendering overlay

java.lang.RuntimeException: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: shaders/program/mffs:glitch_blit.json
	at dev.su5ed.mffs.render.RenderPostProcessor.reloadPostProcessPass(RenderPostProcessor.java:67) ~[mffs-5.1.9-all.jar%23226!/:5.1.9] {re:classloading}
	at dev.su5ed.mffs.setup.ModClientSetup.lambda$onResourceReload$2(ModClientSetup.java:127) ~[mffs-5.1.9-all.jar%23226!/:5.1.9] {re:classloading}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.96.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: shaders/program/mffs:glitch_blit.json
	at net.minecraft.resources.ResourceLocation.m_245413_(ResourceLocation.java:281) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.EffectInstance.<init>(EffectInstance.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.PostPass.<init>(PostPass.java:31) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading}
	at dev.su5ed.mffs.render.RenderPostProcessor.reloadPostProcessPass(RenderPostProcessor.java:64) ~[mffs-5.1.9-all.jar%23226!/:5.1.9] {re:classloading}
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
nullStacktrace:
	at dev.su5ed.mffs.render.RenderPostProcessor.reloadPostProcessPass(RenderPostProcessor.java:67) ~[mffs-5.1.9-all.jar%23226!/:5.1.9] {re:classloading}
	at dev.su5ed.mffs.setup.ModClientSetup.lambda$onResourceReload$2(ModClientSetup.java:127) ~[mffs-5.1.9-all.jar%23226!/:5.1.9] {re:classloading}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1385) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23242!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.96.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources, SolarFlux

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.7.0-060700-generic
	Java Version: 20.0.2, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1851375624 bytes (1765 MiB) / 3523215360 bytes (3360 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900XT 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.78
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: Navi 21 [Radeon RX 6950 XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 16640.00
	Graphics card #0 deviceId: 0x73a5
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 48081.50
	Virtual memory used (MB): 23721.92
	Swap memory total (MB): 24040.75
	Swap memory used (MB): 5481.75
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.1.96
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 6950 XT (navi21, LLVM 15.0.7, DRM 3.56, 6.7.0-060700-generic) GL version 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1, AMD
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glBindTexture(non-gen name)' x 164
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 3900XT 12-Core Processor
	OptiFine Version: OptiFine_1.20.1_HD_U_I6
	OptiFine Build: 20231221-120401
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1
	OpenGlRenderer: AMD Radeon RX 6950 XT (navi21, LLVM 15.0.7, DRM 3.56, 6.7.0-060700-generic)
	OpenGlVendor: AMD
	CpuCount: 24
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		loader-47.1.47.jar slf4jfixer PLUGINSERVICE 
		loader-47.1.47.jar object_holder_definalize PLUGINSERVICE 
		loader-47.1.47.jar runtime_enum_extender PLUGINSERVICE 
		loader-47.1.47.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		loader-47.1.47.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@47.1
		minecraft@47.1
		javafml@47.1
	Mod List: 
		rsrequestify-1.20.1-2.3.3.jar                     |RSRequestify                  |rsrequestify                  |2.3.3               |DONE      |Manifest: NOSIGNATURE
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |DONE      |Manifest: NOSIGNATURE
		clienttweaks-forge-1.20-11.1.0.jar                |Client Tweaks                 |clienttweaks                  |11.1.0              |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		rechiseled-1.1.5c-forge-mc1.20.jar                |Rechiseled                    |rechiseled                    |1.1.5c              |DONE      |Manifest: NOSIGNATURE
		scena-forge-1.0.103.jar                           |Scena                         |scena                         |1.0.103             |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.20.1-20.1.24.jar                      |HammerLib                     |hammerlib                     |20.1.24             |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		mffs-5.1.9-all.jar                                |Modular Force Field System    |mffs                          |5.1.9               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.2-13.0.0.4.jar                  |Clumps                        |clumps                        |13.0.0.4            |DONE      |Manifest: NOSIGNATURE
		MoreMobGriefingOptions-1.20.1-2.0.4.jar           |More MobGriefing Options      |moremobgriefingoptions        |2.0.4               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-neoforge.jar             |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.0.jar                          |Placebo                       |placebo                       |8.6.0               |DONE      |Manifest: NOSIGNATURE
		useitemonblockevent-1.20.1-1.0.0.2.jar            |Use Item on Block Event       |useitemonblockevent           |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		BasicNetherOres-forge-1.20.1-9.1.1.jar            |Basic Nether Ores             |bno                           |9.1.1               |DONE      |Manifest: NOSIGNATURE
		jumbofurnace-1.20.1-4.0.0.5.jar                   |Jumbo Furnace                 |jumbofurnace                  |4.0.0.5             |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		fusion-1.1.0c-forge-mc1.20.1.jar                  |Fusion                        |fusion                        |1.1.0c              |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.20.1-14.0.27.jar             |CraftTweaker                  |crafttweaker                  |14.0.27             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.5.19.jar                     |Mekanism                      |mekanism                      |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.5.19.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.5              |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.96-universal.jar                |NeoForge                      |forge                         |47.1.96             |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |DONE      |Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |DONE      |Manifest: NOSIGNATURE
		out_of_sight-1.20.1-1.0.3.jar                     |Out of Sight                  |out_of_sight                  |1.20.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		AmbientSounds_FORGE_v5.3.5_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.5               |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.20.1-10.4.5.19.jar            |Mekanism: Additions           |mekanismadditions             |10.4.5              |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.7.1.jar                      |Jade                          |jade                          |11.7.1              |DONE      |Manifest: NOSIGNATURE
		bluepower-1.20.1-0.10.323-alpha-universal.jar     |Blue Power                    |bluepower                     |0.10.323-alpha      |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.16_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.16             |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.20.1-20.1.5.jar                 |Solar Flux Reborn             |solarflux                     |20.1.5              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		pipez-1.20.1-1.2.5.jar                            |Pipez                         |pipez                         |1.20.1-1.2.5        |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.20.1-8.0.2.jar                    |Fast Workbench                |fastbench                     |8.0.2               |DONE      |Manifest: NOSIGNATURE
		WorldPreGenerator-1.20.1-4.0.0.jar                |World Pre Generator           |world_pre_generator           |4.0.0               |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.6.2               |DONE      |Manifest: NOSIGNATURE
		railcraft-reborn-1.20.1-1.0.10.jar                |Railcraft Reborn              |railcraft                     |1.0.10              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.5.19.jar                |Mekanism: Tools               |mekanismtools                 |10.4.5              |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.20.1-8.0.1.jar                      |FastFurnace                   |fastfurnace                   |8.0.1               |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.20.1-forge-1.109.3.jar               |CC: Tweaked                   |computercraft                 |1.109.3             |DONE      |Manifest: NOSIGNATURE
		light-overlay-8.0.0-forge.jar                     |Light Overlay                 |lightoverlay                  |8.0.0               |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar              |ItemPhysic                    |itemphysic                    |1.7.0               |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.10.0.jar                   |Refined Storage Addons        |refinedstorageaddons          |0.10.0              |DONE      |Manifest: NOSIGNATURE
		CobbleForDays-1.8.0.jar                           |Cobble For Days               |cobblefordays                 |1.8.0               |DONE      |Manifest: NOSIGNATURE
		chisels-and-bits-forge-1.4.145.jar                |chisels-and-bits              |chiselsandbits                |1.4.145             |DONE      |Manifest: NOSIGNATURE
		morered-1.20.1-4.0.0.4.jar                        |More Red                      |morered                       |4.0.0.4             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4eecb3db-cd43-4bf9-8425-1557af21872a
	FML: 47.1
	NeoForge: net.neoforged:47.1.96
```

**Comment by Su5eD** [comment]
I suspect this is a bug in NeoForge, as the code itself appears to be correct. Please use MinecraftForge 47.1.3 on Minecraft 1.20.1 for the best results.
